### ISSUE TITLE
404 when deploying to azure

### ISSUE THREAD

**Issue by ncecere** [covidsafe/Backend#39]
I have used the quick start to create my Azure services but not matter what when I deploy this application I always get a 404 error.  It doesn't appear the backend is starting in azure from what I can tell.  I'm new to Azure so I'm looking for some assistance in deploying the backend.

**Comment by corygehr** [comment]
Hi @ncecere. How are you deploying the backend? Are you directly deploying from Visual Studio?

Assuming you don't receive an error it should be fine. You may want to attempt to hit the /swagger endpoint to see if the documentation appears. If that's the case, it's a safe bet it has deployed successfully.
